### ISSUE TITLE
We should add functionality for jumping!

### ISSUE THREAD

**Issue by mgyliu** [mgyliu/dsci-100-demo-f23#1]
This is a feature request from Maggie. I think we should let characters jump in the game!

**Comment by Moe-Jala** [comment]
i disagree

**Comment by edl05** [comment]
no

**Comment by wenshanli1231** [comment]
:)

**Comment by Gecko-Fish** [comment]
Needs coyote time

**Comment by LisaWang88** [comment]
O.o

**Comment by BettyL0702** [comment]
ʕ•̀ o • ʔ

**Comment by Cindyy8** [comment]
o.O

**Comment by EricaYLe3** [comment]
I have no idea what I’m doing !

**Comment by ErinGunn32** [comment]
▒▒▒▒▒▒▒▒▒▄▄▄▄▒▄▄▄▒▒▒
▒▒▒▒▒▒▄▀▀▓▓▓▀█░░░█▒▒
▒▒▒▒▄▀▓▓▄██████▄░█▒▒
▒▒▒▄█▄█▀░░▄░▄░█▀▀▄▒▒
▒▒▄▀░██▄░░▀░▀░▀▄▓█▒▒
▒▒▀▄░░▀░▄█▄▄░░▄█▄▀▒▒
▒▒▒▒▀█▄▄░░▀▀▀█▀▓█▒▒▒
▒▒▒▄▀▓▓▓▀██▀▀█▄▀▒▒▒▒
▒▒█▓▓▄▀▀▀▄█▄▓▓▀█▒▒▒▒
▒▒▀▄█░░░░░█▀▀▄▄▀█▒▒▒
▒▒▒▄▀▀▄▄▄██▄▄█▀▓▓█▒▒
▒▒█▀▓█████████▓▓▓█▒▒
▒▒█▓▓██▀▀▀▒▒▒▀▄▄█▀▒▒
▒▒▒▀▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
